### ISSUE TITLE
Lottie icon works in development but disappears after building with vite

### ISSUE THREAD

**Issue by jellyo-o** [Gamote/lottie-react#108]
I am having some issues with using Lottie-react `"lottie-react": "^2.4.0"`. The icon shows up when I run the development environment with `vite` but when I build it with `vite build` and then view the page, the lottie icon doesn't show up. No idea if this is a bug or I'm doing it wrong. No errors in the console either. Any help is appreciated. Thanks in advance

This is are snippets of my code:

```jsx
import Lottie from 'lottie-react';
import uploadCloud from "../assets/uploadCloud.json"
```
```jsx
<div className="h-10 w-full">
  <Lottie
    lottieRef={lottieRef}
    animationData={uploadCloud}
    loop={false}
    autoplay={false}
    className='h-16 w-16'
  />
  <span>Click or drag files here to upload</span>
</div>
```

**Comment by arindammitra06** [comment]
Does this help? I was facing similar issue. Reference [https://stackoverflow.com/questions/75339797/next-js-lottie-cannot-add-property-completed-object-is-not-extensible](url)

import * as animationData from './anim.json';
Replace by:
import animationData from './anim.json';

**Comment by phil294** [comment]
Facing the same issue, except we also get error output:
```
client-shared.js:2058 TypeError: Cannot read properties of undefined (reading 'useState')
    at useLottie2 (lottie1.js:166:27)
    at Lottie3 (lottie1.js:484:22)
    at Nh (vendor.js:12852:8)
```
in
```
React.useState(false)
```
no idea how this is possible??

That is to say, this is with custom chunking logic. *Without* code splitting, I get

```
client-shared.js:2058 TypeError: Cannot add property __complete, object is not extensible
    at Object.completeData (vendor.js:41526:42)
    at workerStart (vendor.js:41613:39)
    at Object.postMessage (vendor.js:41060:11)
    at Object.completeAnimation (vendor.js:41679:24)
    at AnimationItem.setupAnimation (vendor.js:42104:19)
    at AnimationItem.setParams (vendor.js:42088:14)
    at Object.loadAnimation2 [as loadAnimation] (vendor.js:42750:18)
    at Object.loadAnimation (vendor.js:44814:31)
    at loadAnimation3 (vendor.js:57087:65)
    at vendor.js:57096:23
```
in
```
                animationData.__complete = true;
```
And when I make the import a `React.lazy(() => import('lottie-react'))`, I get various
```
client-shared.js:2058 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Wj (https://navi.dev.gn/js/mastertemplate/vendor.js:14503:54)
```
So I guess it's safe to say this library doesn't work with Vite builds :-/

**Comment by pzehrel** [comment]
```tsx


// lazy import json file
const data = import('@/assets/animate/data.json')

// get assets images urls
// When Vite builds, asset URLs become HTTP URLs. Filenames will include a hash.
const assets = import.meta.glob('@/assets/animate/**/*.{png,jpg,jpeg}', { eager: true, import: 'default', query: '?url' })


export async function transformAnimateJsonData(data: any, assets: any): Promise<any> {

  const json = { ...await data } // Destructuring will cause an error; Lottie does not accept Module type objects.

  for (const asset of json.assets) {
    // This directly modifies the return object of `import()`, without deep copying, which is equivalent to modifying the cache of the ESM module. Therefore, it only needs to be modified once.
    if (!asset.u) {
      return json
    }

    const relativepath = asset.u + asset.p
    for (const key in assets) {
      if (key.endsWith(relativepath)) {
        asset.u = '' // folder
        asset.p = assets[key] // filename
        break
      }
    }
  }

  return json
}


//  ahooks useRequest
const fetcher = useRequest(async () => transformAnimateJsonData(data, assets))

<Lottie animationData={fetcher.data} />
```

**Comment by timofei-iatsenko** [comment]
Could be related to this https://github.com/Gamote/lottie-react/issues/130

Since Vite uses diffrent strategy for transforming/bundling for dev/build it could cause the issue described.

**Comment by Gamote** [comment]
Three different things are in this thread, so one at a time.

The disappearing icon and the `Cannot add property __complete, object is not extensible` error come from `import * as data from "./anim.json"`: that hands the engine a frozen module namespace, and lottie-web writes a flag onto it. v3 always copies the object it is given before the engine sees it, so this no longer throws. The default import stays the right way to bring a JSON file in, as @arindammitra06 said, since a namespace object may not carry the animation's fields the same way under every bundler:

```tsx
import animationData from "./assets/uploadCloud.json";
import { Lottie } from "lottie-react";

<Lottie src={animationData} loop={false} autoplay={false} className="h-16 w-16" />
```

For images that get hashed file names in a production build (@pzehrel), `assetsPath` points the engine at where they live, and rewriting the asset URLs in the object before passing it, as your snippet does, works with `src` too.

The `useState of undefined` and `insertBefore` traces with custom `manualChunks` are a chunking problem in the build configuration (React ending up in a different chunk from code that imports it), not something the animation data or the library changes; if it still shows up on v3, please open a fresh issue with a reproduction and I will look.

Closing as fixed for the reported cause.

> [!NOTE]
> ### 🎉 lottie-react v3 is out
>
> A rewrite, and the things people asked for the most are in: `src` fetches a URL or takes the object, `loop`, `speed` and `direction` are reactive, `seek` moves by frame, marker, percent or seconds, an accessible control bar, scroll and in-view interactions, `LottieSvg` and `LottieLight` builds, server rendering with no dynamic import, React 18 and 19, only what you import ships, and more.
>
> [Docs and live examples](https://lottiereact.com) · [Migration guide](https://lottiereact.com/docs/migration), every v2 surface mapped to its v3 home.
